file_format: "1"
id: my_keyboard
name: My Split Keyboard
type: shield
url: https://github.com/yahyaGoblin/zmk-config
requires:
  - xiao_ble//zmk
features:
  - keys
siblings:
  - my_keyboard_left
  - my_keyboard_right