manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 6765b2f4bfef28d4e6566a5cbef39eb25b98ca36
      import: app/west.yml
  self:
    path: config